#!/bin/bash
export GOOGLE_SERVICE_ACCOUNT_URL=cuenta@duplicity-413012.iam.gserviceaccount.com
export GOOGLE_SERVICE_JSON_FILE="/home/cristian/duplicity_creds.json"
export GNUPGHOME='/home/cristian/.gnupg'
export PASSPHRASE="12345"

GPG_KEY="095C14A9D545ACCD"

if [ $# -eq 0 ]; then
	echo "Debes decirme donde restaurar la copia"
	exit
fi

if [ -z "$1" ]; then
	echo "La carpeta no puede ser nada"
	exit
fi

if [[ $1 != /* ]]; then
	echo "Pasame la ruta correctamente /ruta"
	exit
fi

duplicity restore --encrypt-sign-key="$GPG_KEY" gdrive://${GOOGLE_SERVICE_ACCOUNT_URL}?myDriveFolderID=1Angqhqo9osBDxUhDh_E75ubIGHDd1gPx $1  >> /var/log/duplicity/gdrive_log_restore.txt 2>> /var/log/duplicity/error_gdrive_log_restore.txt

unset GOOGLE_SERVICE_ACCOUNT_URL
unset GOOGLE_SERVICE_JSON_FILE
unset GNUPGHOME
unset PASSPHRASE
